apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy007
  labels:
    app: autodeploy007
  namespace: namespace-workflow-1699958760895
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy007
  template:
    metadata:
      labels:
        app: autodeploy007
    spec:
      containers:
        - name: autodeploy007
          image: acrworkflow1699958760895.azurecr.io/image-workflow-1699958760895:latest
          ports:
            - containerPort: 5000